scrapperorg/client

src/constants/paths.ts, src/screens/login/index.tsx, src/screens/recoverPassword/RecoverForm.tsx, src/screens/recoverPassword/index.tsx, src/screens/resetPassword/ResetForm.tsx, src/screens/resetPassword/TokenValidation.tsx, src/screens/resetPassword/index.tsx, src/services/api/AuthApiService.ts
- recover password, validate token, reset password methods on auth api service
- recover password screen
-- form
-- success message
-- error handling
- reset password screen
-- token validation
--- valid and invalid handling
-- reset form
-- reset success message
=> reset Password implementation

src/components/topbar/index.tsx
=> Initial topbar icons layout

src/components/layout/index.tsx, src/components/layout/styled.tsx
=> Increasing content width

src/components/genericTableRow/index.tsx, src/screens/monitor/components/documentTable/index.tsx
=> Highlighting the new docs rows

src/contexts/authContext.tsx, src/hooks/useApiService.ts, src/screens/monitor/components/content/index.tsx, src/screens/monitor/components/documentTable/index.tsx, src/screens/monitor/components/sourcesSelector/index.tsx, src/screens/monitor/context/index.tsx, src/screens/monitor/hooks/useDocumentsFilters.ts, src/services/api/DocumentApiService.ts, src/services/api/UserApiService.ts, src/services/api/dtos/auth.ts, src/services/api/dtos/document.ts, src/services/api/dtos/project.ts
- userApiService for updating user sources of interest
- sources Selector
- allow usePaginatedApiService to be passed arguments
- useDocumentsFilters for filters state
=> Documents filtering

package.json, src/components/formatedDate/index.tsx, src/screens/monitor/components/documentTable/index.tsx, yarn.lock
=> Parse publication date

src/components/genericTableRow/index.tsx, src/components/layout/index.tsx
Fixing layout by increasing table width (available for desired dimensions - 1920x1080).
=> Layout fix

src/contexts/interactiveComponentsContext.tsx, src/screens/documentDetails/components/assignResponsibleModal/index.tsx, src/screens/documentDetails/components/content/index.tsx, src/screens/documentDetails/components/documentActivity/index.tsx, src/screens/documentDetails/context/index.tsx, src/screens/documentDetails/hooks/useDocumentDetails.ts, src/services/api/DocumentApiService.ts, src/services/api/UserApiService.ts
- assign responsible modal
- useDocumentDetails hooks
- assignResponsible service method
- getAssignableResponsibles service method
=> Assign responsible

src/screens/documentDetails/components/assignResponsibleModal/index.tsx, src/screens/documentDetails/components/content/index.tsx, src/screens/documentDetails/components/documentActivity/index.tsx, src/screens/documentDetails/hooks/useDocumentDetails.ts, src/services/api/DocumentApiService.ts
=> Set deadline

src/components/modal/profile/index.tsx, src/constants/roles.ts, src/helpers/formatters.ts
=> Replace mock name modal

src/components/protectedByRole/index.tsx, src/contexts/authContext.tsx, src/router/components/privateRoute/index.tsx, src/router/components/roleProtectedRoute/index.tsx
Fixing routing issue by having the isAuthenticated value taken from the `token`, and not from the `user`.
=> Routing issue

package.json, src/components/pdfViewer/index.tsx, src/screens/documentDetails/components/documentGeneralData/index.tsx, yarn.lock
=> added pdf viewer

Dockerfile, docker-compose.yml
- remove NGinx from the image and add `yarn start` 
- add docker compose
=> Add docker compose for client

package.json, src/screens/monitor/components/content/index.tsx, src/screens/monitor/components/sourcesSelector/index.tsx, src/screens/monitor/context/index.tsx, yarn.lock
- long polling is now paused when dropdown is opened
- long polling is now cancelled when page is changes
=> fixed long polling

src/components/genericTableRow/index.tsx, src/components/layout/index.tsx, src/components/sidebar/components/SidebarTitle.tsx, src/components/sidebar/index.tsx, src/components/sidebar/sideMenuItems.ts, src/components/sidebar/styled.tsx, src/screens/documentDetails/components/documentActivity/index.tsx
- added sidebar title
- added new sidebar buttons
- fixed some UI issues
=> Sidebar improvements

src/components/circularProgressIndicator/index.tsx, src/components/documentTable/index.tsx, src/components/genericTableRow/index.tsx, src/screens/documentDetails/components/content/index.tsx, src/screens/documentDetails/components/documentProcessedData/index.tsx
[Document details page improvements](https://trello.com/c/gPbjXfnC/253-document-details-page-improvements)
[Fixed monitor Status text](https://trello.com/c/HTOk8gaK/250-defect-monitor-stare-is-written-inanaliza-instead-of-in-analiza)
=> document details page improvements

src/screens/projectDetails/components/projectGeneralData/index.tsx, src/screens/projectDetails/components/projectHeader/index.tsx
=> hiding table if source is not of interest

src/screens/projectsSearch/components/projectsTable/index.tsx, src/screens/projectsSearch/components/searchForm/index.tsx
removed check for project that presents interest and removed registation number from results table
=> project search ui updates

docker-compose.yml
The network is already defined.
=> api_default as pre-existing network

src/components/downloadDocumentButton/index.tsx, src/locales/ro.json, src/screens/documentDetails/components/content/index.tsx, src/screens/documentDetails/components/documentActivity/index.tsx, src/screens/documentDetails/components/documentAttachments/index.tsx, src/screens/documentDetails/components/documentGeneralData/index.tsx, src/screens/documentDetails/components/documentProcessedData/index.tsx, src/screens/monitor/hooks/useDocuments.ts, src/services/api/DocumentApiService.ts
=> reordering and changing buttons logic

src/screens/profileDetails/components/content/index.tsx
=> profile photo ui improvement
